spring.application.name=spring-boot-demo
amazon.dynamodb.endpoint=${DYNAMODB_ENDPOINT:http://localhost:8000}
amazon.dynamodb.accessKey=${AWS_ACCESS_KEY_ID:dummy}
amazon.dynamodb.secretKey=${AWS_SECRET_ACCESS_KEY:dummy}

# エラーページにスタックトレースを表示する
server.error.include-stacktrace=always
# エラーページにメッセージを表示する
server.error.include-message=always
# エラーページに例外の詳細を表示する
server.error.include-exception=true