spring.application.name=spring-boot-demo
amazon.dynamodb.endpoint=${DYNAMODB_ENDPOINT:http://localhost:8000}

# エラーページにスタックトレースを表示する
server.error.include-stacktrace=always
# エラーページにメッセージを表示する
server.error.include-message=always
# エラーページに例外の詳細を表示する
server.error.include-exception=true