spring.application.name=spring-boot-demo
amazon.dynamodb.endpoint=${DYNAMODB_ENDPOINT:http://localhost:8000}

# エラーページにスタックトレースを表示する
server.error.include-stacktrace=always
# エラーページにメッセージを表示する
server.error.include-message=always
# エラーページに例外の詳細を表示する
server.error.include-exception=true

# Actuator設定
management.endpoints.web.exposure.include=prometheus,health,info,metrics
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true