server.error.include-stacktrace=never
server.error.include-exception=false
amazon.dynamodb.endpoint=https://dynamodb.ap-northeast-1.amazonaws.com
amazon.dynamodb.accessKey=${AWS_ACCESS_KEY_ID}
amazon.dynamodb.secretKey=${AWS_SECRET_ACCESS_KEY} 